### PR TITLE
Initial version of installer

### PR DESCRIPTION
**Pull request by natdan**

### CODE REVIEW

**Comment by nebbian** [comment]
Hi @natdan,

Thanks for doing this work.

Can you provide the source code for this installer please?  This will allow us to keep track of source code changes in a more logical way.

**Comment by natdan** [comment]
You missed my post on cel's web site? Anyway - here it is: https://github.com/natdan/rbx-toolset/tree/master/robox-extensions-installer

At first I though to create PR to put source in your repo, but then decided to extend it from installer for Slicer Extension only to installer to ... well a few things: 

- Slicer Extension (your repo)
- Remote Robox or networking robox (Raspberry Pi - or any Java enabled OS computer next to Robox printer)
- GCode preview
- Any future extension

Do give it a go when you have chance. At the moment it is not smart enough to check if installation is correct and which 'version' is installed but we can add that as well. I was thinking adding extra file with commit SHA as version of installed stuff, too. 

Feel free to contribute it to at any moment. Also, next I'll make PR where your CuraEngine script invokes another jar (sitting next to it) which will do the same job as your perl scrip + CuraEngine script.

**Comment by nebbian** [comment]
Perhaps you could add your repo as a submodule?  I would prefer to have the source easily downloadable for someone just coming across the RoboxSlicerExtension git repo.

**Comment by natdan** [comment]
"Perhaps you could add your repo as a submodule?" - what do you mean by that? And which one? [Gcode-preview](https://github.com/natdan/gcode-preview) (which I would like to add as option to install), [java-simple-serial-connector](https://github.com/natdan/java-simple-serial-connector) fork for remote robox or installer [itself](https://github.com/natdan/rbx-toolset)? The installer, kind of, sits between all of those and yours here. 

And, by all means - do link the installer repo in Readme or anywhere else you think is appropriate! :)

**Comment by nebbian** [comment]
Hey @natdan,

> "Perhaps you could add your repo as a submodule?" - what do you mean by that? And which one? 

Check out the git submodule documentation here:
https://git-scm.com/docs/git-submodule

I think it would be appropriate in our case.

**Comment by nebbian** [comment]
Also, do you have a list of everything that the installer does, or tries to do?

**Comment by natdan** [comment]
re: submodule - oh, why not. 

> Also, do you have a list of everything that the installer does, or tries to do?

Currently it does following:
- checks if selected dir is AM installation
- checks if <AM dir>/Common/Cura/CuraEngine_orig exists and if so allows 'Uninstall' button
- for installation checks (again) if above exists and if not copies CuraEngine to CuraEngine_orig (otherwise does nothing)
- creates Slic3r/Config dir and downloads (from master from your repo) CuraEngine, slic3r_postprocess.pl to <AM dir>/Common/Cura and Robox_slic3r_config_bundle.ini to <AM dir>/Slic3r/Config

Creating Slic3r dir is not a quite right thing to do as, I suspect, on Windows there might already be dir called like that (on OSX it is called Slic3r.app) (for older versions of AM).

Does that make sense? If there's anything else for it to do - please let me know. As I said, I'm planning to make a list of what is to be installed with tick boxes next to each item so user can select what to add. Also, at the same time, I am planning refactor code internally for each item to have their own installer class.

**Comment by nebbian** [comment]
Cool, that sounds good.  Can you please add to your pull request some instructions for installation, including uninstall steps?  By this I mean modifying the README file.  I assume that the user still has to go into Slic3r and import the config.

**Comment by natdan** [comment]
Something like this?

**Pull request merged**
